### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by RaphaelStArnaud**
| Q                             | R
| ----------------------------- | -------------------------------------------
| Correction de bugs ?          | Non
| Nouvelle Fonctionnalité ?     | Non
| Tickets (_issues_) concernés  | #311 ; #218 ; #511 ; #517 ; #516

### CODE REVIEW

**Comment by RignonNoel** [comment]
+#: Mailer/ApplicationMailer.php:55
+msgid "All positions available for {0} have been filled"
+msgstr ""

-> has been

**Comment by RignonNoel** [comment]
Lot of place with "Edit the ...", "Archive the ...", "Restore the ..."
-> delete "the"

**Comment by RignonNoel** [comment]
#: Template/Missions/index.ctp:4
msgid "New Mission"
msgstr "New Mission"

-> New mission

**Comment by RignonNoel** [comment]
#: Mailer/ApplicationMailer.php:55
msgid "All positions available for {0} have been filled"
msgstr "Toutes les positions disponibles pour {0} ont été comblés."

positions -> place
comblés -> comblées

**Comment by RignonNoel** [comment]
#: Model/Table/OrganizationsTable.php:113 Model/Table/ProjectsTable.php:119
#: Model/Table/UsersTable.php:134
msgid "Is not an url (Ex : http://website.ca)."
msgstr "Le lien web n'est pas valide (Ex : http://website.ca)."

Website -> Siteweb

**Comment by RignonNoel** [comment]
#: Model/Table/UsersTable.php:221
msgid "Please use only letters (a-z), numbers, periods, and underscore."
msgstr ""
"Vous ne pouvez utiliser que des lettres(a-z,A-Z), des chiffres, des points "
"et un tiret bas."

un tiret bas -> des tiret bas

**Comment by RignonNoel** [comment]
#: Template/Applications/accepted.ctp:9
msgid "Warning! There is only 1 position left on the mission"
msgstr "Attention! Il ne reste qu'une seule position pour cette mission"

position -> place

**Comment by RignonNoel** [comment]
#: Template/Applications/accepted.ctp:15
msgid "edit your mission"
msgstr "Modifier votre mission"

Respecter les majuscules

**Comment by RignonNoel** [comment]
#: Template/Applications/accepted.ctp:13
msgid "If you want to add more candidates {0} {1} accepting this candidate"
msgstr ""
"Si vous voulez augmenter le nombre de places disponible {0} {1} d'accepter "
"ce candidat"

Après débat on va mettre un 's' a disponible

**Comment by RignonNoel** [comment]
#: Template/Applications/accepted.ctp:35 Template/Applications/rejected.ctp:19
msgid "Please insert your password to finalize your choice"
msgstr "Veuillez insérer votre mot de passe pour finaliser votre choix"

insérer -> saisir

**Comment by RignonNoel** [comment]
#: Template/Cell/Sidebar/user.ctp:16
msgid ""
"This avatar is a gravatar linked with your email. If you want change your "
"avatar, go on {0}"
msgstr ""
"Cet avatar est un gravatar liée avec votre courriel. Si vous voulez changer "
"votre avatar, aller sur {0}"

liée -> lié

**Comment by RignonNoel** [comment]
#: Template/Element/Missions/addForm.ctp:19 Template/Missions/edit.ctp:27
#: Template/Pages/submit.ctp:31
msgid "What are the student requirements to work on the project?"
msgstr "Quel est le niveau technique requis pour postuler sur votre projet ?"

sur votre projet -> sur le projet

**Comment by RignonNoel** [comment]
#: Template/Element/News/news-table.ctp:6
msgid "Info"
msgstr "Info"

Info -> Informations

**Comment by RignonNoel** [comment]
#: Template/Email/html/accepted_on_application.ctp:21
#: Template/Email/text/accepted_on_application.ctp:20
msgid "The mentor will contact you with further information"
msgstr "Le mentor vous contactera avec de l'information supplémentaire"

Le mentor prendra contact avec vous pour de plus ample informations

**Comment by RignonNoel** [comment]
#: Template/Email/html/approve_project.ctp:19
#: Template/Email/text/approve_project.ctp:18
msgid "Your project [{0}] has been approved"
msgstr "Votre projet [{0}] a été apporuvé"

apporuvé -> approuvé

**Comment by RignonNoel** [comment]
#: Template/Missions/edit_mentor.ctp:6
msgid "Edit mentor"
msgstr "Modifié le mentor"

Modifié -> Modifier

**Comment by RignonNoel** [comment]
#: Template/Missions/view.ctp:119
msgid "Full company details"
msgstr "Fiche complète"

Fiche complète -> Détails entreprise

**Comment by RignonNoel** [comment]
#: Template/Organizations/add.ctp:10
msgid "Add Organization"
msgstr "Ajouter l'organisation"

Ajouter une organisation

**Comment by RignonNoel** [comment]
#: Template/Organizations/add.ctp:13 Template/Organizations/edit.ctp:10
#: Template/Organizations/submit.ctp:16 Template/Projects/add.ctp:12
#: Template/Projects/edit.ctp:11 Template/Projects/submit.ctp:23
#: Template/Universities/add.ctp:14 Template/Universities/edit.ctp:21
#: Template/Users/add.ctp:24 Template/Users/edit.ctp:54
msgid "http(s)://website.com"
msgstr "http(s)://website.com"

site web

**Comment by RignonNoel** [comment]
#: Template/Organizations/admin_index.ctp:34
msgid "Not approved"
msgstr "Non approuvé"

Non approuvée

**Comment by RignonNoel** [comment]
#: Template/Organizations/admin_index.ctp:41
msgid "Not rejected"
msgstr "Non rejeté"

Non rejetée

**Comment by RignonNoel** [comment]
#: Template/Organizations/index.ctp:72
#: Template/Organizations/my_organizations.ctp:67
#: Template/Organizations/view.ctp:30 Template/Projects/index.ctp:95
#: Template/Projects/my_projects.ctp:90 Template/Users/view.ctp:36;73
msgid "Pending Validation"
msgstr "En attente de validation"

En validation

**Comment by RignonNoel** [comment]
#: Template/Organizations/submit.ctp:11
msgid ""
"You will be redirected to your organization page to create projects once you "
"submit your organization."
msgstr ""
"Vous serez redirigé vers la page de votre organisation pour créer des "
"projets lorsque vous aurai soumit votre organisation."

Corrige ;)

**Comment by RignonNoel** [comment]
#: Template/Organizations/submit.ctp:13
msgid "Submit Organization"
msgstr "Soumettre l'organisation"

Soumettre une organisation

**Comment by RignonNoel** [comment]
#: Template/Pages/home.ctp:15
msgid "Welcome to Maison Logiciel Libre (ML2)"
msgstr "Bienvenue à la Maison du Logiciel Libre ( ML² )"

pas d'espace dans les parenthèses

**Comment by RignonNoel** [comment]
#: Template/Pages/home.ctp:64
msgid "Become a sponsor "
msgstr "Devenir un commanditaire"

problem of space

**Comment by RignonNoel** [comment]
#: Template/Projects/add.ctp:8
msgid "Add Project"
msgstr "Ajouter projet"

Ajouter le projet

**Comment by RignonNoel** [comment]
#: Template/Projects/add.ctp:23 Template/Projects/submit.ctp:39
msgid ""
"Select organizations associated with the project. Leave blank if no "
"organizations"
msgstr ""
"Sélectionnez le(s) organisation(s) associée(s) avec le projet. Laissez vide "
"s'il n'y a pas d'organisation"

Enlever le pluriel, sinon ça on risque de tomber.

**Comment by RignonNoel** [comment]
#: Template/Projects/edit.ctp:8
msgid "Edit Project"
msgstr "Modifier projet"

On met des "le" ou pas?

**Comment by RignonNoel** [comment]
#: Template/Projects/index.ctp:7
msgid ""
"A project can be of development or system administration and it can be owned "
"by zero, one or more organizations. It may provide mission to students."
msgstr ""
"Un projet peut consister en du développement ou de l'administration de "
"système et il peut être détenue par zéro, une ou plusieurs organisations. Il "
"peut fournir une mission aux étudiants."

des missions aux étudiants
Correction de l'anglais nécessaire aussi du coups

**Comment by RignonNoel** [comment]
#: Template/Users/edit.ctp:31
msgid "Are you a student?"
msgstr "Êtes-vous un étudiant"

????

**Comment by RignonNoel** [comment]
#: Template/Users/edit.ctp:35
msgid "Would you like to be a mentor?"
msgstr "Devenir mentor?"

Voulez vous devenir mentor?

**Comment by RignonNoel** [comment]
#: Template/Users/register.ctp:9
msgid ""
"Letters (a-z), numbers, periods, underscore, and between 3 and 16 characters"
msgstr ""
"Lettres (a-z,A-Z), nombres, points, tiret bas et entre 3 et 16 caractères."

tiretS

**Comment by RignonNoel** [comment]
#: Template/Users/view.ctp:52
msgid "Organizations joined"
msgstr "Organisations rejointe"

organisations rejointes

**Comment by RignonNoel** [comment]
C-C-C-C-COMBO BREAKER!!

**Comment by RaphaelStArnaud** [comment]
Finish Him!

**Comment by nicbou** [comment]
FATALITY

Good job gents :)

**Pull request merged**
