### PR TITLE
Recover password

### PR DESCRIPTION
**Pull request by RignonNoel**
| Q                             | R
| ----------------------------- | -------------------------------------------
| Correction de bugs ?          | Non
| Nouvelle Fonctionnalité ?     | Oui
| Tickets (_issues_) concernés  | #322 

You need to :
 - Migrate DB
 - Populate hashTypes
 - Configure Email in Mailer and config file 'app.php'

### CODE REVIEW

**Comment by RignonNoel** [comment]
Problem of buffer in travis... Waiting for work on.

**Comment by RignonNoel** [comment]
-1.2% in coverage because we don't know how to test the sending email for the moment.

**Comment by simon-begin** [comment]
Check this : http://stackoverflow.com/questions/11523135/how-to-test-cakeemail-is-called-from-a-model

**Comment by RaphaelStArnaud** [comment]
Change UrlHelper with Router::build

**Comment by RignonNoel** [comment]
Router is change.
Test doesn't fix for the moment.

**Pull request merged**
