### PR TITLE
Members and owners of organization

### PR DESCRIPTION
**Pull request by RaphaelStArnaud**
| Q                             | R
| ----------------------------- | -------------------------------------------
| Correction de bugs ?          | Non
| Nouvelle Fonctionnalité ?     | Oui
| Tickets (_issues_) concernés  | #226

### CODE REVIEW

**Comment by simon-begin** [comment]
Change the button icon for a fa-plus and add the form-control class in the input select in add owner and add member

**Comment by RignonNoel** [comment]
Add a owner to quit an organization

**Comment by RignonNoel** [comment]
It's good, but : 
 - If the owner want quit and is the last -> redirect to isRejected
 - Just add comments on organizations:quit if possible. But not very important...

**Comment by RignonNoel** [comment]
Move to develop, need to close the release.

**Pull request closed without merging**
